title: baluchicken-apt-repo
email: balintmolnar91@gmail.com
description: >- 
  This project is ment to be an aptrepo hosted by github pages
baseurl: ""
url: "https://baluchicken.github.io/aptrepo"
github_username: baluchicken

# Build settings
theme: minimal
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/